Functions, Parameters, and Fitting for Teaching Calculus
========================================================

**Date**: Tuesday, January 8th, 2013; 9:00am - 4:00pm

**Location**: [Marriott Marquis San Diego](http://www.marriott.com/hotels/maps/travel/sandt-san-diego-marriott-marquis-and-marina/) in the [Carlsbad/Cardiff Rooms](http://www.marriott.com/hotelwebsites/us/s/sandt/SANDT_PDF/SANDT%20All-FloorDiagram2012-Color.pdf): South Tower --- Level 3

[**GitHub Web Page**](http://dtkaplan.github.com/JMM2013)

#### [Description](http://www.causeweb.org/workshop/jmm13_mosaic/)

> This one-day workshop is designed to help instructors move toward teaching introductory calculus in a modeling- and data-oriented way. The parameters of basic functions are often treated casually in introductory calculus, as if they were a nuisance or merely fodder for the chain rule. In the first half of the workshop, we'll show how to interpret them physically, how to relate them to data, and how to use them for model building. The second half emphasizes polynomial approximation, the relationship between Taylor series and model fitting, and model building using information about derivatives. A small, general purpose mathematical toolkit suffices to build and interpret compelling models in a very wide range of settings spanning economics, biology, physics, etc. We'll provide in-class activities, assignments, student project topics, and example exam questions. Both paper-and-pencil as well as computer-oriented approaches (using R, Sage, or Mathematica) will be featured, drawing on the materials developed through the NSF-supported Project MOSAIC, which aims to construct strong connections in teaching modeling, calculus, statistics, and computation. Participants are encouraged to bring a laptop. If you don't currently use software for teaching calculus, we'll set you up with the free R system running through a web browser.

##### Workshop Leaders:
* Danny Kaplan, Macalester College
* Randall Pruim, Calvin College

##### Support:
* A grant to [Project MOSAIC](http://www.mosaic-web.org) from the US National Science Foundation, NSF DUE-0920350
* [CAUSE](http://www.causeweb.org/): The Consortium for the Advancement of Undergraduate Statistics Education
* MAA: The Mathematical Association of America

#### Handouts at the Workshop:

* [R/mosaic Cheat Sheet](http://dtkaplan.github.com/Statistical-Modeling-A-Fresh-Approach/Blog/EnoughR.pdf)
* [Eyeballing Parameters](Notes/Eyeballing-Parameters.pdf)
* [Tukey's Bulge Rules](Handouts/TukeyBulge.pdf)

#### Other Resources:

* Dan Flath's site for ["Applied Calculus"](http://danflath.com/math-135-applied-math/), Math 135 at Macalester, including a day-by-day syllabus.
* Ben Baumer's activity on fitting power laws using [Tukey's Power Rule and the Ladder of Powers](http://www.math.smith.edu/~bbaumer/mth247/labs/transformations.html)

## Schedule and Outline

Workshop = Work + Shop

Outline of the day: Four themes

 1. Anatomy of a (Mathematical) Model
 2. Models and Calculus (What does Calculus tell me about my model?)
 3. Fitting Models (How do I use data?)
 4. Model Creation (What model(s) should I fit?)

 
We'll divide the day up into 4 sessions with approximately this schedule:

 * 9-10:15  Session 1
 * 10:15-10:30  Break
 * 10:30-11:45  Session 2
 * 11:45-1:15  Lunch at the Marina Kitchen in the Marriott.  Free to participants.
 * 1:10-2:30  Session 3
 * 2:30-2:45  Break
 * 2:45-4:00  Session 4
 
### Introduction

  What is a model?  What is modeling?
  
### Anatomy of a Model: Functions and Parameters

[Introduction](Notes/Introduction.html)

[Introductory activity](Activities/Introduction/introductory-activity.html) (15 min) 

#### Interactive: Technology: Accessing the web server and RStudio (15 min) 

* Introduction to enough R to load and plot data
    * `fetchData()`
    * `plotPoints()`
    * Assignment with `=` or `<-`
    
#### Compiling the list of functions and parameterizations (15 min) 

At this point, just enter the forms, without much discussion.  

Use R Markdown to record these live and to demo how R Markdown works.

------


#### ACTIVITY: [Eyeballing Parameters](Notes/Eyeballing-Parameters.html) (20 min)

* Load in the data files and find the parameters.  Data files illustrate several of the function types:


### Summary
Create and display a document summarizing the findings.  

* A template document on [Calculus Functions and their Parameters](functions-parameters.html)

### Calculus and Models

##### Catch up on function and parameter document (5min)

##### Calculus Operations (40 min)

###### Differentiation 

1. Find the flow [from PREP 2012](http://prep2012.mosaic-web.org/Topics/OrangeJuiceFlow/OrangeJuice.html)
2. [Linear and Quadratic approximations via derivatives](Notes/Derivs-and-Approximations.html). **TO DO: put `slideX0` in `fetchData()` repository

**Going Further**
* [Kepler and Mars](Notes/Kepler-Mars.html) (Task 3)

###### Integration 

1. [Integration by Eye](https://dl.dropbox.com/u/5098197/Math135/In-Class/hiv-graph.pdf)
2. [From flow to volume](Notes/Flow-to-Volume.html) Given the flow, find the volume.  (From StartR)



**Going Further**
* Traffic light capacity (integrating a hill function). [from PREP 2012](http://prep2012.mosaic-web.org/Topics/Integration/Traffic-Light-Capacity.html)
* RMS approximation.  Showing that the constant approx is not as good as the linear is not as good as the quadratic. (See final part of [linear and quadratic appoximations](Notes/Derivs-and-Approximations.html))

### Fitting Models 

Document: [How to get a quick estimate of sampling variation](Notes/Sampling-Variation.html)


* Best fit models
  * The criteria for `fitModel`
  * **TO DO** Write a function that fits a function form to a given $f(x)$ using least squares.  Have it sample $f(x)$ on a given range.


Manifest versus latent function forms:
* Income-Housing (manifest form)
* Cooling water --- fitting the two exponentials.
* Hawaii tides --- what is the period?

Sampling Distribution
* Sampling and resampling distributions
* The standard error

### Creating Models

ACTIVITY: [How to get a quick estimate of sampling variation](Notes/Sampling-Variation.html)

**Going Further**
* [Fitting a probability model](Likelihood.html)

#### Noon 

Lunch at the Marina Kitchen in the Marriott. Free to participants. [Lunch menu](Logistics/lunch.html)

Manifest versus latent function forms:
* Income-Housing (manifest form)
* Space-Shuttle


* Linearization
    * Hooke's Law
    * Newton's Law of cooling ([Stan's paper](Resources/Stan-Cooling.pdf) showing different functional forms.)
    * Bi-linear: Idea gas law, law of mass action
* Polynomials, Taylor series and least squares
* Sine waves and orthogonality: our emphasis on polynomials pre-dates the development of wave- and oscillation-based technology.


##### Activity: 

* `mTaylor` applet.
```{r eval=FALSE,message=FALSE}
fetchData("mTaylor.R")
mTaylor( exp(-.2*x)*sin(x)~x,xlim=c(0,10))
```
Task: Use this to create a lesson plan on the quality of an approximation.



##### Lecture: Power laws and where they come from: (15 min)

* Units & Dimensional analysis
    * Analysis of the Trinity bomb yield
* Allometrics
    * Species-Area data `"http://www.math.smith.edu/~bbaumer/mth247/SpeciesArea.csv"`
    * [Body Mass Index](ABSI-activity.html)

**Going Further**:
* [Engine RPM versus power](https://dl.dropbox.com/u/5098197/Math135/In-Class/engine-speed.pdf).


Functions in two variables


##### Important Functional Forms
* The Ideal Gas Law and the Law of Mass Action [PREP 2012](http://dl.dropbox.com/u/5098197/Math135/In-Class/ideal-gas-activity1.pdf)
* [Cobb-Douglas](http://prep2012.mosaic-web.org/Topics/Cobb-Douglas/cobb-douglas.html) and other power-laws, e.g. body shape: [ABSI activity](ABSI-activity.html)
* The landscape functions: [mountain](http://dl.dropbox.com/u/5098197/Math135/Figures/cairo-solar.png), valley, [hillside](http://dl.dropbox.com/u/5098197/Math135/Figures/1000px-Body_mass_index_chart.png), amphitheater
* Random functions

##### The modeling polynomial: 2nd order in two variables

* [picking model terms](http://dl.dropbox.com/u/5098197/Math135/In-Class/poly2d.pdf)
* Transformations
* Fitting and interpreting
   * Used car prices

##### Partial derivatives

###### Body Fat Data [see Victor Addona's slides](http://www.mosaic-web.org/go/MCAST/materials/Sept-10-2010/Addona_MCAST_Sept_10.pdf)
* What's the relationship between `BodyFat` and `Height`?  
* What if we include `Weight`?
* What if `Abdomen` circumference is included, too?

* [Celebrity Divorce](http://dl.dropbox.com/u/5098197/Math135/In-Class/celebrity-divorce.pdf): is it a reasonable model?
* [Eyeballing interactions](http://dl.dropbox.com/u/5098197/Math135/In-Class/eyeball-partials.pdf)


Optimization

* [Health policy example](http://prep2012.mosaic-web.org/Topics/Optimization/QALY3.html)


#### 4:00 Adjourn


-------------



### Orphaned Ideas

* [Hill function](http://prep2012.mosaic-web.org/Topics/Functions/hillFunctions.html)   
* [Maximum heart rate versus age](https://dl.dropbox.com/u/5098197/PREP2012/max-hr.pdf).  Get the data.  [Wikipedia article](http://en.wikipedia.org/wiki/Heart_rate)
* Add a `plotPath()` function to mosaic: `plotPath( c(x=cos(t),y=sin(t))~t, t.lim=c(0,2*pi))`

